test_dataset:
  name: matterport3d
  root_path: 
  list_path: datasets/matterport3d_test.txt
  args:
    height: 512
    width: 1024
    repeat: 1
    augment_color: False
    augment_flip: False
    augment_rotation: False
  batch_size: 1
  num_workers: 4

model:
  name: panda
  args:
    midas_model_type: vits
    fine_tune_type: inference
    min_depth: 0.01
    max_depth: 10.0
    lora: True
    train_decoder: True
    lora_rank: 4

median_align: False

load_weights_dir: 