train_dataset_1:
  name: structured3d
  root_path: 
  list_path: datasets/Structure3D_train.txt
  args:
    height: 504
    width: 1008
    repeat: 1
    augment_color: True
    augment_flip: True
    augment_rotation: True
  batch_size: 1
  num_workers: 4

train_dataset_2:
  name: deep360
  root_path: 
  list_path: datasets/deep360_train.txt
  args:
    height: 504
    width: 1008
    repeat: 1
    augment_color: True
    augment_flip: True
    augment_rotation: True
  batch_size: 1
  num_workers: 4

val_dataset:
  name: structured3d
  root_path:
  list_path: datasets/Structure3D_test.txt
  args:
    height: 504
    width: 1008
    repeat: 1
    augment_color: False
    augment_flip: False
    augment_rotation: False
  batch_size: 4
  num_workers: 4

model:
  name: panda
  args:
    midas_model_type: vitl
    fine_tune_type: hypersim
    min_depth: 0.01
    max_depth: 1.0
    lora: True
    train_decoder: True
    lora_rank: 4

loss: [ {'type': 'silog', 'params': {'loss_weight': 1.0}}, 
        {'type': 'gradient', 'params': {'loss_weight': 1.0, 'scale_num': 4}},
        {'type': 'epnl', 'params': {'loss_weight':5.0, 'random_num':32, 'batch_limit':8, 'lower_bound':0.125, 'upper_bound':0.5}}]

optimizer:
  lr: 1.e-4
epoch_max: 20
log_frequency: 40

epoch_val: 10
epoch_save: 10

